### PR TITLE
LocationScreen UI is cut off

### PR DESCRIPTION
**Pull request by ad2969**
Addressing issue #111 
- Made styling of the 'view' part of the input an option
- Hopefully fixed the overflow in the directions screen (tested on simulator iOS - iPhone 8)

Screen Shot 2020-03-28 at 2 58 17 PM

### CODE REVIEW

**Comment by Asiapenguin** [comment]
This is what it looks right now for my S7. Looks good!

91004771_207738020487752_1109052592681385984_n

**Comment by Asiapenguin** [comment]
@andrchoi @Wennxn If you guys can take a quick look with your devices, that would be nice as well. I wont wait for forever though

**Comment by Asiapenguin** [comment]
@mxnyee Reminder to check if some things can potentially break by his styling.

**Comment by andrchoi** [comment]
Looks good for me too. Couldn't find anything that broke.
Screenshot_20200403-185241

**Pull request merged**
